# Generated by Django 3.2.8 on 2022-06-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20220603_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_comment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
